apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: peerscout-stable
  namespace: peerscout
spec:
  suspend: true
  imageRepositoryRef:
    name: peerscout-stable
    namespace: peerscout
  policy:
    semver:
      range: '*'
