apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-auth--stg
  namespace: data-hub
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: airflow-auth--stg
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: data-team/data-hub/airflow-auth--stg
