scheduledQueries:
  - dataPipelineId: remove_old_manuscript_version_all_records
    bigQuery:
      projectName: 'elife-data-pipeline'
      sqlQuery: |-
        DELETE FROM `elife-data-pipeline.{ENV}.manuscript_version_all` AS t_delete
        WHERE EXISTS (
          SELECT 1
          FROM (
            SELECT
              key,
              MAX(imported_timestamp) AS latest_imported_timestamp
            FROM (
              SELECT
                TO_JSON_STRING((SELECT AS STRUCT t_data.version_id, t_data.long_manuscript_identifier)) AS key,
                provenance.imported_timestamp,
              FROM (
                SELECT *
                FROM `elife-data-pipeline.{ENV}.manuscript_version_all`
              ) AS t_data
            )
            GROUP BY key
          ) AS t_source
          WHERE TO_JSON_STRING((SELECT AS STRUCT  t_delete.version_id, t_delete.long_manuscript_identifier)) = t_source.key
            AND t_delete.provenance.imported_timestamp < t_source.latest_imported_timestamp
        )

  - dataPipelineId: remove_old_person_all_records
    bigQuery:
      projectName: 'elife-data-pipeline'
      sqlQuery: |-
        DELETE FROM `elife-data-pipeline.{ENV}.person_all` AS t_delete
        WHERE EXISTS (
          SELECT 1
          FROM (
            SELECT
              key,
              MAX(imported_timestamp) AS latest_imported_timestamp
            FROM (
              SELECT
                TO_JSON_STRING((SELECT AS STRUCT t_data.* EXCEPT(provenance, modified_timestamp))) AS key,
                provenance.imported_timestamp,
              FROM `elife-data-pipeline.{ENV}.person_all` AS t_data
            )
            GROUP BY key
          ) AS t_source
          WHERE TO_JSON_STRING((SELECT AS STRUCT t_delete.* EXCEPT(provenance, modified_timestamp))) = t_source.key
            AND t_delete.provenance.imported_timestamp < t_source.latest_imported_timestamp
        )

  - dataPipelineId: remove_old_489_datascience_editor_keywords_records
    bigQuery:
      projectName: 'elife-data-pipeline'
      sqlQuery: |-
        DELETE FROM `elife-data-pipeline.{ENV}.489_datascience_editor_keywords` AS t_delete
        WHERE EXISTS (
          SELECT 1
          FROM (
            SELECT
              key,
              MAX(imported_timestamp) AS latest_imported_timestamp
            FROM (
              SELECT
                TO_JSON_STRING((SELECT AS STRUCT t_data.* EXCEPT(provenance, imported_timestamp, date_generated, date_generated_info))) AS key,
                imported_timestamp,
              FROM `elife-data-pipeline.{ENV}.489_datascience_editor_keywords` AS t_data
            )
            GROUP BY key
          ) AS t_source
          WHERE TO_JSON_STRING((SELECT AS STRUCT t_delete.* EXCEPT(provenance, imported_timestamp, date_generated, date_generated_info))) = t_source.key
            AND t_delete.imported_timestamp < t_source.latest_imported_timestamp
        )

  - dataPipelineId: remove_old_editorial_manuscript_consultation_session
    bigQuery:
      projectName: 'elife-data-pipeline'
      sqlQuery: |-
        DELETE FROM `elife-data-pipeline.{ENV}.editorial_manuscript_consultation_session` AS t_delete
        WHERE EXISTS (
          SELECT 1
          FROM (
            SELECT
              key,
              MAX(imported_timestamp) AS latest_imported_timestamp
            FROM (
              SELECT
                TO_JSON_STRING((SELECT AS STRUCT t_data.* EXCEPT(provenance, imported_timestamp, date_generated_info))) AS key,
                imported_timestamp,
              FROM `elife-data-pipeline.{ENV}.editorial_manuscript_consultation_session` AS t_data
            )
            GROUP BY key
          ) AS t_source
          WHERE TO_JSON_STRING((SELECT AS STRUCT t_delete.* EXCEPT(provenance, imported_timestamp, date_generated_info))) = t_source.key
            AND t_delete.imported_timestamp < t_source.latest_imported_timestamp
        )

  - dataPipelineId: remove_old_gmail_thread_details_records
    bigQuery:
      projectName: 'elife-data-pipeline'
      sqlQuery: |-
        DELETE FROM `elife-data-pipeline.{ENV}.gmail_thread_details` AS t_delete
        WHERE EXISTS (
          SELECT 1
          FROM (
            SELECT
              key,
              MAX(imported_timestamp) AS latest_imported_timestamp
            FROM (
              SELECT
                TO_JSON_STRING(STRUCT(user_id, threadId)) AS key,
                imported_timestamp,
              FROM `elife-data-pipeline.{ENV}.gmail_thread_details` AS t_data
            )
            GROUP BY key
          ) AS t_source
          WHERE TO_JSON_STRING(STRUCT(t_delete.user_id, t_delete.threadId)) = t_source.key
            AND t_delete.imported_timestamp < t_source.latest_imported_timestamp
        )
  - dataPipelineId: remove_old_rp_reviews_and_elife_assessment_emails
    bigQuery:
      projectName: 'elife-data-pipeline'
      sqlQuery: |-
        DELETE FROM `elife-data-pipeline.{ENV}.rp_reviews_and_elife_assessment_emails` AS t_delete
        WHERE EXISTS (
          SELECT 1
          FROM (
            SELECT
              key,
              MAX(imported_timestamp) AS latest_imported_timestamp
            FROM (
              SELECT
                email_id AS key,
                imported_timestamp,
              FROM `elife-data-pipeline.{ENV}.rp_reviews_and_elife_assessment_emails` AS t_data
            )
            GROUP BY key
          ) AS t_source
          WHERE t_delete.email_id = t_source.key
            AND t_delete.imported_timestamp < t_source.latest_imported_timestamp
        )

  - dataPipelineId: remove_old_reviewer_info_records
    bigQuery:
      projectName: 'elife-data-pipeline'
      sqlQuery: |-
        DELETE FROM `elife-data-pipeline.{ENV}.779_datascience_reviewer_info_all` AS t_delete
        WHERE EXISTS (
          SELECT 1
          FROM (
            SELECT
              key,
              MAX(imported_timestamp) AS latest_imported_timestamp
            FROM (
              SELECT
                TO_JSON_STRING((
                  SELECT AS STRUCT
                    t_data.manuscript_id,
                    t_data.manuscript_revision_no,
                    t_data.long_manuscript_identifier,
                    t_data.reviewer_person_id
                )) AS key,
                imported_timestamp,
              FROM (
                SELECT *
                FROM `elife-data-pipeline.{ENV}.779_datascience_reviewer_info_all`
              ) AS t_data
            )
            GROUP BY key
          ) AS t_source
          WHERE
            TO_JSON_STRING((
              SELECT AS STRUCT
                t_delete.manuscript_id,
                t_delete.manuscript_revision_no,
                t_delete.long_manuscript_identifier,
                t_delete.reviewer_person_id
            )) = t_source.key
            AND t_delete.imported_timestamp < t_source.latest_imported_timestamp
        )

  - dataPipelineId: remove_old_people_orcid_profile_records
    bigQuery:
      projectName: 'elife-data-pipeline'
      sqlQuery: |-
        DELETE FROM `elife-data-pipeline.{ENV}.people_orcid_profile`
        WHERE imported_timestamp < (
          SELECT MAX(imported_timestamp)
          FROM `elife-data-pipeline.{ENV}.people_orcid_profile`
        )
